## 20-NumpyGiris:

In [1]:
import numpy as np

## numpy array:

In [2]:
liste1 = [20,30,40]

In [3]:
type(liste1)

list

In [4]:
# liste olan bir nesne numpy ile numpy dizisine çevrilebilir.

In [5]:
np.array(liste1)

array([20, 30, 40])

In [6]:
matrixListesi = [[10,20,30], [20,30,40], [30,40,50]]

In [7]:
type(matrixListesi)

list

In [8]:
matrixListesi[0]

[10, 20, 30]

In [9]:
matrixListesi[0][1]

20

In [11]:
np.array(matrixListesi)  ## numpy array'e matrix gibi çeviriyor

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [12]:
## Hazır dizi oluşturma metodları:

## arange:

In [13]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,10,2)   #step size: 2

array([0, 2, 4, 6, 8])

## zeros:

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## linspace:

In [21]:
# verilen iki sayı arasında, son parametrede verilen sayı kadar eşit boşuklu sayı seçer.

In [24]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [25]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [26]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [29]:
np.linspace(0,40, 9)   #  formula is =  (lastnum - firstnum) / count-1 =  step size

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40.])

## eye:

In [30]:
# diagonal yapısı 1 olan, diğer elemanları 0 olan bir matrix, i.e. identity matrix oluşturmak için kullanılır

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## random:

In [34]:
np.random.randn(4)   #rastgele rakamlardan oluşan bir dizi

array([-0.29886396,  0.36602619, -1.05918176,  0.62310576])

In [35]:
np.random.randn(4,4)

array([[-0.37009946, -0.90813221, -0.76461263,  0.42561085],
       [ 1.56493824,  1.93451394, -1.26583286,  0.99181097],
       [ 1.16442946,  0.33980755, -0.64844672, -0.38597584],
       [-0.86452605,  0.44314183,  0.40954832, -0.91524906]])

In [43]:
np.random.randint(1,10)  # bu range'deki br int'i döndürür

8

In [44]:
np.random.randint(1,10,5)

array([2, 8, 5, 8, 4])

In [45]:
np.random.randint(1,200,5)

array([191,  67,  93,  53,  92])

In [46]:
numpydizi1 = np.arange(30)

In [47]:
numpydizi1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [48]:
randomdizi1 = np.random.randint(0,100,30)

In [49]:
randomdizi1

array([84, 69, 57,  6, 89, 26, 68, 25,  1, 97, 30, 73, 94, 82, 29, 55, 52,
       77, 77, 59,  0,  1, 63, 26,  7,  8, 23, 51, 10, 64])

# Numpy dizi metodları:

In [52]:
numpydizi1.reshape(5,6)  # reshape için verilen değerler dizinin eleman sayısına uygun olmalı

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [60]:
numpydizi1.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [61]:
numpydizi2 = np.arange(0,60)
numpydizi2.reshape(5,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [62]:
numpydizi1.max()

29

In [63]:
randomdizi1.max()

97

In [64]:
randomdizi1.min()

0

In [65]:
randomdizi1.argmax()

9

In [66]:
randomdizi1.argmin()

20

In [67]:
# dizinin attribute'ları da alınabilir

In [68]:
numpydizi1.shape

(30,)

In [70]:
reshapeDizi1= numpydizi1.reshape(5,6)

In [71]:
reshapeDizi1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [72]:
reshapeDizi1.shape

(5, 6)