## 21-NumpyOperasyonlar

In [1]:
import numpy as np

In [3]:
dizi1 = np.arange(0,15)

In [4]:
dizi1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
dizi1[5]  ## Nasıl ki listelerden index 0'dan başlar; numpy dizilerinde de index 0'dan başlar

5

In [10]:
dizi1[3:8]  #  başlangıç indexini alıyor, son bitirme index'inin rakamını almıyor

array([3, 4, 5, 6, 7])

In [11]:
dizi1[3:8] = -5

In [12]:
dizi1

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [13]:
dizi2 = np.arange(0,24)

In [14]:
dizi2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
slicingDizisi = dizi2[4:9]

In [16]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [18]:
slicingDizisi[:] = 700  # [:] ile gösterilince tek tek dizinin bütün elemanlarının 700' eşitlenir

In [19]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [20]:
dizi2

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [23]:
## Burda garib olan durum şu ki:  slicing ile aldığımız dizinin içindeki rakamlar da değişti !!
## Orijinal dizinin bir parçasında yapılan değişikliklerin hepsi orijinal diziye yansıtılıyor

In [24]:
## Orijinal diziyi bozmadan slicing almak mümkün mü?

In [25]:
dizi3 = np.arange(0,24)

In [26]:
dizi3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [27]:
dizi3kopyasi = dizi3.copy()

In [29]:
dizi3kopyasiSlicing = dizi3kopyasi[3:6]

In [30]:
dizi3kopyasiSlicing

array([3, 4, 5])

In [31]:
dizi3kopyasiSlicing[:] = 800

In [32]:
dizi3kopyasiSlicing

array([800, 800, 800])

In [33]:
dizi3kopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [34]:
dizi3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix:

In [35]:
ornekListe= [[10,20,30], [20,30,40], [30,40,50]]

In [36]:
matrixDizisi = np.array(ornekListe)

In [37]:
matrixDizisi

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [38]:
matrixDizisi[0]

array([10, 20, 30])

In [39]:
matrixDizisi[1][2]

40

In [41]:
matrixDizisi[1,2] # row :1, column: 2

40

In [42]:
matrixDizisi[1:,2]

array([40, 50])

In [43]:
matrixDizisi[0:,2]

array([30, 40, 50])

In [44]:
matrixDizisi[2:,2]

array([50])

In [45]:
matrixDizisi[2:,1:]

array([[40, 50]])

In [46]:
matrixDizisi[2:,0:]

array([[30, 40, 50]])

In [52]:
yeniListe = [ [0, 1, 2, 3,4], [5,6,7,8,9],[10,11,12,13,14],[15,16,17, 18,19],[20,21,22,23,24]]

In [53]:
yeniMatrix = np.array(yeniListe)

In [54]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
yeniMatrix[2]

array([10, 11, 12, 13, 14])

In [58]:
yeniMatrix[[4,2,0]]  # Bu nolu rowları getirir

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

## Operasyonlar

In [60]:
# Toplama, çıkarma, büyüktür vs. gibi işlemleri yapmak için

In [63]:
yeniDizi2 = np.random.randint(1,100,20)

In [64]:
yeniDizi2

array([82, 86, 74, 72, 82, 82, 31, 58, 47, 57,  8, 82, 51, 81, 27, 17, 82,
       37, 48, 50])

In [66]:
sonucDizisi = yeniDizi2 > 24

In [67]:
sonucDizisi

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True])

In [69]:
yeniDizi2[sonucDizisi]  # sadece 24'ten büyük rakamları filtreleyip veriyor

array([82, 86, 74, 72, 82, 82, 31, 58, 47, 57, 82, 51, 81, 27, 82, 37, 48,
       50])

In [70]:
yeniDizi2[yeniDizi2 > 24]

array([82, 86, 74, 72, 82, 82, 31, 58, 47, 57, 82, 51, 81, 27, 82, 37, 48,
       50])

In [71]:
dizi3 = np.arange(0,24)

In [72]:
dizi3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [73]:
dizi3 + dizi3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [76]:
dizi3 * dizi3    # elemanların kendi karesini alır

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [77]:
dizi3 - dizi3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [78]:
dizi3 / dizi3

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [80]:
np.sqrt(dizi3)   # dizinin elemanlarının karekökünü bulmak için

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [81]:
np.max(dizi3)

23